### ISSUE TITLE
Support Us page

### ISSUE THREAD

**Issue by anandology** [farmhill-learning/farmhill-learning.org#4]
Migrate the [support us](https://farmhill-learning.org/support-us) page to the new website.

**Comment by anandology** [comment]
Added the support us page.

https://new.farmhill-learning.org/support-us/

Couple of changes from the existing page:
- Made _Pay Instantly with Razorpay_ is the first option
- Added heading _Why should you support us?_
- Images sizes are slightly different

Please review the text and also the layout both on laptop and mobile phone. Let me know if you would like any changes. @venugvgk

**Comment by venugvgk** [comment]
This looks good!
